const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const CURRICULUM_DIR = path.join(__dirname, '../../../curriculum');
const SQL_OUTPUT_PATH = path.join(__dirname, 'curriculum_sync.sql');
const DB_NAME = 'arduino-db';

// Helper to escape SQL strings
const esc = (str) => {
    if (!str) return '';
    return str.replace(/'/g, "''");
};

function main() {
    console.log('📦 Scanning curriculum files...');

    if (!fs.existsSync(CURRICULUM_DIR)) {
        console.error(`❌ Curriculum directory not found: ${CURRICULUM_DIR}`);
        process.exit(1);
    }

    const files = fs.readdirSync(CURRICULUM_DIR).filter(f => f.endsWith('.md'));
    let sqlStatements = [];

    // Clear existing lessons generated by this process? 
    // For now, we use INSERT OR REPLACE. 
    // Note: We might want to clear old lessons if we want a clean slate, but let's stick to UPSERT.

    sqlStatements.push(`-- Generated by sync_curriculum_cli.js`);
    sqlStatements.push(`BEGIN TRANSACTION;`);

    files.forEach(file => {
        // Filename format: week-01-gpio-led.md
        const match = file.match(/^week-(\d+)-(.+)\.md$/);
        if (!match) {
            console.warn(`⚠️  Skipping file (invalid naming): ${file}`);
            return;
        }

        const weekNum = parseInt(match[1], 10);
        const slug = match[2];
        const weekId = `week-${weekNum.toString().padStart(2, '0')}`;
        const lessonId = `l-${weekNum.toString().padStart(2, '0')}-01`;

        const filePath = path.join(CURRICULUM_DIR, file);
        const content = fs.readFileSync(filePath, 'utf-8');

        // Extract Title from first line
        const lines = content.split('\n');
        const firstLine = lines[0] || '';
        let title = firstLine.replace(/^#\s*/, '').trim();

        // If title has "Tuần X: ...", clean it up slightly if needed, or keep it.
        // Provide a cleaner title for the 'weeks' table if possible.
        // Example: "Tuần 4: Phần mềm Hệ thống Nhúng - Analog Input/Output (ADC & PWM)"
        // It's a bit long. Let's keep it as is for correctness, or let the user decide later.

        console.log(`Processing: ${weekId} -> ${title}`);

        // UPDATE weeks table
        // We only update title and ensure it exists. 
        // We preserve other fields like topic_id, course_id if we can, but since we are UPSERTING, we need values.
        // Since we don't know the topic mapping easily without hardcoding, 
        // we might choose to ONLY UPDATE existing weeks, or INSERT with defaults.
        // Let's UPDATE 'weeks' title if it exists, or Insert with default 'topic-01' if not.
        // Actually, to be safe and avoid breaking foreign keys or existing structure, 
        // let's try to UPDATE title only for the week.

        sqlStatements.push(`
            UPDATE weeks 
            SET title = '${esc(title)}', 
                overview = '${esc(title)}' 
            WHERE id = '${weekId}';
        `);

        // INSERT OR REPLACE lessons
        // We treat the file as the first lesson of the week.
        sqlStatements.push(`
            INSERT OR REPLACE INTO lessons (id, week_id, order_index, title, content, board_support, is_published)
            VALUES (
                '${lessonId}',
                '${weekId}',
                1,
                '${esc(title)}',
                '${esc(content)}',
                'both',
                1
            );
        `);
    });

    sqlStatements.push(`COMMIT;`);

    console.log(`📝 Writing SQL to ${SQL_OUTPUT_PATH}...`);
    fs.writeFileSync(SQL_OUTPUT_PATH, sqlStatements.join('\n'));

    console.log(`🚀 Executing SQL on D1 (${DB_NAME})...`);
    try {
        // Use --file to avoid shell limits
        // Run from apps/workers directory where wrangler.toml is located
        const workersDir = path.join(__dirname, '..');
        // SQL path relative to CWD (apps/workers) => scripts/curriculum_sync.sql
        const sqlRelativePath = 'scripts/curriculum_sync.sql';

        execSync(`npx wrangler d1 execute ${DB_NAME} --local --file="${sqlRelativePath}"`, {
            stdio: 'inherit',
            cwd: workersDir
        });
        console.log('✅ Sync complete!');
    } catch (e) {
        console.error('❌ Failed to execute SQL.');
        console.error(e.message);
        process.exit(1);
    }
}

main();
