-- Weeks Seed
INSERT OR REPLACE INTO weeks (id, course_id, week_number, topic_id, title, overview, is_published) VALUES ('week-00', 'course-01', 0, 'topic-01', 'Tuần 0: Nhập môn Điện tử & Linh kiện cơ bản', '**Thời lượng**: 2 tiết lý thuyết + 1 tiết thực hành **Mục tiêu**: Hiểu kiến thức điện tử cơ bản trước khi bắt đầu lập trình Arduino **💡 Mẹo nhớ**: Dùng **tam giác VIR** - che đại lượng cần tìm, còn lại là công thức! **"Bà Nâu Đi Ra Cầu Vàng Xem Xanh Tím Xám Trắng"** **"Bad Boys Ravish Our Young Girls But Violet Gives Willingly"** ⚠️ **CẢNH BÁO**: LED LUÔN CẦN ĐIỆN TRỞ HẠN DÒNG! Không có điện trở → LED cháy! **Tuần tiếp theo**: Arduino Uno & GPIO - Điều khiển LED bằng code!', 1);
INSERT OR REPLACE INTO weeks (id, course_id, week_number, topic_id, title, overview, is_published) VALUES ('week-01', 'course-01', 1, 'topic-01', 'Tuần 1: Tổng quan Hệ thống Nhúng & GPIO (Điều khiển LED)', '**Thời lượng**: 3 tiết lý thuyết + 2 tiết thực hành **Mục tiêu**: Làm quen Arduino Uno, hiểu cấu trúc chương trình, điều khiển LED cơ bản **Tuần tiếp theo**: LED 7 đoạn & Thiết kế hệ thống nhúng', 1);
INSERT OR REPLACE INTO weeks (id, course_id, week_number, topic_id, title, overview, is_published) VALUES ('week-02', 'course-01', 2, 'topic-02', 'Tuần 2: Thiết kế Hệ thống Nhúng & LED 7 Đoạn', '**Thời lượng**: 3 tiết lý thuyết + 2 tiết thực hành **Mục tiêu**: Hiểu phương pháp thiết kế, điều khiển LED 7 đoạn đơn và module 4 số ⚠️ **Quan trọng**: Khi mua LED 7 đoạn, hãy kiểm tra loại CC hay CA để viết code đúng logic! 💡 **Mẹo nhớ**: Số 8 bật tất cả (0x7F), số 1 chỉ bật b và c (0x06) **Tuần tiếp theo**: Tuần 3 - Nút nhấn & Keypad (INPUT_PULLUP, Debounce, Edge Detection)', 1);
INSERT OR REPLACE INTO weeks (id, course_id, week_number, topic_id, title, overview, is_published) VALUES ('week-03', 'course-01', 3, 'topic-02', 'Tuần 3: Phần cứng Hệ thống Nhúng - Nút nhấn & Keypad', '**Thời lượng**: 3 tiết lý thuyết + 2 tiết thực hành **Mục tiêu**: Đọc nút nhấn chính xác, xử lý debounce, điều khiển bằng keypad ⚠️ **Lưu ý**: Logic **đảo ngược** so với trực giác! HIGH = không nhấn, LOW = nhấn. **Tuần tiếp theo**: Tuần 4 - Analog Input/Output (ADC & PWM)', 1);
INSERT OR REPLACE INTO weeks (id, course_id, week_number, topic_id, title, overview, is_published) VALUES ('week-04', 'course-01', 4, 'topic-02', 'Tuần 4: Phần mềm Hệ thống Nhúng - Analog Input/Output (ADC & PWM)', '**Thời lượng**: 3 tiết lý thuyết + 2 tiết thực hành **Mục tiêu**: Đọc tín hiệu analog từ potentiometer, điều khiển LED bằng PWM **Tuần tiếp theo**: Tuần 5 - Thực hành tích hợp I/O (Ghép nút + pot + LED + 7-seg)', 1);
INSERT OR REPLACE INTO weeks (id, course_id, week_number, topic_id, title, overview, is_published) VALUES ('week-05', 'course-01', 5, 'topic-03', 'Tuần 5: Thực hành Tích hợp I/O', '**Thời lượng**: 2 tiết lý thuyết + 3 tiết thực hành **Mục tiêu**: Ghép nối pot + nút + LED + 7-seg thành hệ thống hoàn chỉnh **Tuần tiếp theo**: Tuần 6 - Cảm biến trong Hệ thống Nhúng', 1);
INSERT OR REPLACE INTO weeks (id, course_id, week_number, topic_id, title, overview, is_published) VALUES ('week-06', 'course-01', 6, 'topic-03', 'Tuần 6: Cảm biến trong Hệ thống Nhúng', '**Thời lượng**: 3 tiết lý thuyết + 2 tiết thực hành **Mục tiêu**: Đọc và xử lý dữ liệu từ các cảm biến phổ biến 💡 **Mẹo**: Không đọc DHT11 quá nhanh (tối thiểu 2 giây giữa các lần đọc) **Tuần tiếp theo**: Tuần 7 - Serial UART (Giao tiếp nối tiếp)', 1);
INSERT OR REPLACE INTO weeks (id, course_id, week_number, topic_id, title, overview, is_published) VALUES ('week-07', 'course-01', 7, 'topic-04', 'Tuần 7: Giao thức Kết nối Nối tiếp (Serial UART)', '**Thời lượng**: 3 tiết lý thuyết + 2 tiết thực hành **Mục tiêu**: Giao tiếp UART giữa Arduino và PC, Arduino với Arduino ⚠️ **Quan trọng**: Cả 2 bên PHẢI dùng cùng baudrate! 💡 **Lưu ý**: SoftwareSerial có tốc độ giới hạn (~57600 baud) và không thể nhận/gửi đồng thời nhiều cổng. **Tuần tiếp theo**: Tuần 8 - Giao thức I2C', 1);
INSERT OR REPLACE INTO weeks (id, course_id, week_number, topic_id, title, overview, is_published) VALUES ('week-08', 'course-01', 8, 'topic-04', 'Tuần 8: Giao thức Kết nối I2C', '**Thời lượng**: 3 tiết lý thuyết + 2 tiết thực hành **Mục tiêu**: Sử dụng I2C để giao tiếp với LCD và các thiết bị khác 💡 **Lưu ý**: Cần điện trở pull-up 4.7kΩ từ SDA và SCL lên VCC. Nhiều module I2C đã có sẵn. **Tuần tiếp theo**: Tuần 9 - Giao thức SPI', 1);
INSERT OR REPLACE INTO weeks (id, course_id, week_number, topic_id, title, overview, is_published) VALUES ('week-09', 'course-01', 9, 'topic-05', 'Tuần 9: Giao thức Kết nối SPI', '**Thời lượng**: 3 tiết lý thuyết + 2 tiết thực hành **Mục tiêu**: Hiểu SPI và điều khiển thiết bị qua shift register **Tuần tiếp theo**: Tuần 10 - Giao thức 1-Wire', 1);
INSERT OR REPLACE INTO weeks (id, course_id, week_number, topic_id, title, overview, is_published) VALUES ('week-10', 'course-01', 10, 'topic-05', 'Tuần 10: Giao thức 1-Wire (DS18B20)', '**Thời lượng**: 3 tiết lý thuyết + 2 tiết thực hành **Mục tiêu**: Đọc cảm biến nhiệt độ DS18B20 qua giao thức 1-Wire 💡 **Mẹo phân biệt**: Mặt phẳng hướng về bạn, từ trái sang: GND, DQ, VCC **Tuần tiếp theo**: Tuần 11 - WiFi WebServer', 1);
INSERT OR REPLACE INTO weeks (id, course_id, week_number, topic_id, title, overview, is_published) VALUES ('week-11', 'course-01', 11, 'topic-05', 'Tuần 11: Giao tiếp WiFi - Chế độ WebServer', '**Thời lượng**: 3 tiết lý thuyết + 2 tiết thực hành **Mục tiêu**: Điều khiển LED từ xa qua web browser ⚠️ **Arduino Uno KHÔNG có WiFi**. Cần dùng **ESP8266** hoặc **ESP32**. **Tuần tiếp theo**: Tuần 12 - Async WebServer', 1);
INSERT OR REPLACE INTO weeks (id, course_id, week_number, topic_id, title, overview, is_published) VALUES ('week-12', 'course-01', 12, 'topic-05', 'Tuần 12: Giao tiếp WiFi - Chế độ Asynchronous WebServer', '**Thời lượng**: 3 tiết lý thuyết + 2 tiết thực hành **Mục tiêu**: Xây dựng WebServer không đồng bộ, responsive và realtime **Chúc bạn thành công trong hành trình IoT!** 🌟', 1);
